CREATE TABLE BILLETTER
(
    id INTEGER AUTO_INCREMENT NOT NULL,
    film VARCHAR (300) NOT NULL,
    antall VARCHAR (300) NOT NULL,
    fornavn VARCHAR (300) NOT NULL,
    etternavn VARCHAR (300) NOT NULL,
    telefonnr VARCHAR (300) NOT NULL,
    epost VARCHAR (300) NOT NULL,
    PRIMARY KEY (id)
);